### ISSUE TITLE
Extra space may be added in parens

### ISSUE THREAD

**Issue by sirreal** [Automattic/calypso-prettier#12]
Under some conditions an extra space may be added inside a closing paren `)`. Appears to be related with accumulated parens from return expression arrow functions.

Note the extra space at the beginning of the line here:
https://github.com/Automattic/wp-calypso/pull/23483/commits/4ade8eb674338b1f99f3de05c7cce23f80f07ca3

Here's an example:

```js
describe( '#baz()', () => {
	test( 'foobar', async () => {
		jest
			.spyOn( loginActions, 'createSocialUser' )
			.mockImplementation( () => () =>
				Promise.reject( { message: 'An error message', code: 'an_error_code' } )
			 ); //  <--------- extra space
	} );
} );
```

Also happens inside the parens with no line breaks:

```js
describe( '#baz()', () => {
	test( 'foobar', async () => {
		jest
			.spyOn( loginActions, 'createSocialUser' )
			.mockImplementation( () => () => Promise.reject()  );
		//                                                        ^--- extra space
	} );
} );
```

**Comment by jsnajdr** [comment]
Fixed in the 1.13.5 upgrade :tada:
