### ISSUE TITLE
Upstream to prettier/prettier?

### ISSUE THREAD

**Issue by coderkevin** [Automattic/calypso-prettier#13]
I looked and didn't see a PR on prettier/prettier to upstream the `--paren-spacing` option. Is this ready to be done yet? If it were upstreamed as an option with a default of 0, then this fork would no longer have to be maintained, if I'm understanding correctly.

**Comment by samouri** [comment]
Jarda already attempted this: https://github.com/prettier/prettier/pull/2372

**Comment by coderkevin** [comment]
Well that's a shame. Such a simple request. I guess `prettier-miscellaneous` isn't very attractive either because it's very far behind the upstream master branch now.

**Comment by coderkevin** [comment]
If such a fork has to be maintained to be compliant with any WP JS code going forward, perhaps it should be under the WordPress github org? I'm a little surprised the Gutenberg builds aren't using this, but maybe that's why?

**Comment by samouri** [comment]
> Well that's a shame. Such a simple request.

@coderkevin: they have a pretty strong core principle to [resist configuration](https://github.com/prettier/prettier/issues/40).  Even though it stinks for WP, I think it makes sense for the JS community as a whole.  On top of that, one could argue that it is Automattic/WordPress that should adapt its style.

**Comment by coderkevin** [comment]
It sounds like this is a no-go, so I'm closing it. 😞
