### ISSUE TITLE
Upgrade to Prettier 1.16

### ISSUE THREAD

**Issue by bluefuton** [Automattic/calypso-prettier#14]
Would it be possible to upgrade the fork to Prettier 1.16? They're currently on 1.16.4:

https://github.com/prettier/prettier/releases

The Prettier plugin for Sublime Text now requires 1.16 or higher, and regrettably fails with an error on lower versions:

https://github.com/jonlabelle/SublimeJsPrettier/issues/157

cc @jsnajdr

**Comment by jsnajdr** [comment]
Fixed. See:
- https://github.com/Automattic/wp-prettier/releases/tag/wp-1.16.4
- https://github.com/Automattic/wp-calypso/pull/30577

One of the easiest Prettier upgrades ever.

**Comment by bluefuton** [comment]
Thanks @jsnajdr :)
