### ISSUE TITLE
Npm: Add publish access

### ISSUE THREAD

**Issue by sirreal** [Automattic/calypso-prettier#18]
@samouri @jsnajdr Can you give me ([`sirreal`](https://www.npmjs.com/~sirreal)) publish access to the npm package:

https://www.npmjs.com/package/wp-prettier

I've prepped an update to the fork on 2.0.4 and would like to publish:
- https://github.com/Automattic/wp-prettier/releases/tag/wp-2.0.4
- https://github.com/Automattic/wp-prettier/tree/wp-prettier-2.0.4

Demo: https://github.com/Automattic/wp-calypso/pull/41114

cc: @Automattic/team-calypso @sgomes

**Comment by samouri** [comment]
Done

**Comment by sirreal** [comment]
Thanks!

**Comment by curtisbelt** [comment]
@sirreal Latest on https://www.npmjs.com/package/wp-prettier is still 1.19.1 -- was 2.0.4 supposed to be published? Or where is this tracked? Thank you!

**Comment by sirreal** [comment]
`wp-prettier@2.0.4` was published under the [`next` dist-tag](https://www.npmjs.com/package/wp-prettier/v/next). It can be installed as `wp-prettier@next`.

**Comment by sirreal** [comment]
When we're satisfied that the release is working properly, we'll bump the `latest`. I don't have it running on any codebases yet 🙂

**Comment by sirreal** [comment]
@curtisbelt [`wp-prettier@2.0.5`](https://www.npmjs.com/package/wp-prettier) has just been released and is now `latest`.
