### ISSUE TITLE
Integrate with Vcode

### ISSUE THREAD

**Issue by Bowriverstudio** [Automattic/calypso-prettier#21]
**Environments:**

- Prettier Version: 2.0.4

**Steps to reproduce:**

My vcode settings.json is

`{
	// Place your settings in this file to overwrite the default settings
	// PHPCS
	"phpcs.enable": true,
	"phpcs.standard": "WordPress",
	"phpcs.executablePath": "./vendor/bin/phpcs",
	// Run PHP Code Beautifier and Fixer on save
	"phpcbf.onsave": true,
	// null, PSR1, PSR2, Symfony, WordPress etc. You can also point to a phpcs.xml rules file, eg: /file/path/phpcs.xml
	"phpcbf.standard": "WordPress",
	"window.zoomLevel": 1,
	// "workbench.colorTheme": "Default Light+",
	"workbench.colorTheme": "Monokai",
	"editor.fontSize": 14,
	"[javascript]": {
		"editor.defaultFormatter": "vscode.typescript-language-features"
	},
	"[javascriptreact]": {
		"editor.defaultFormatter": "esbenp.prettier-vscode"
	},
	// "[php]": {
	// 	"editor.defaultFormatter": "persoderlind.vscode-phpcbf"
	// },
	"javascript.updateImportsOnFileMove.enabled": "always",
	// "[javascriptreact]": {
	// 	"editor.defaultFormatter": "esbenp.prettier-vscode"
	// },
	// "editor.formatOnSave": true,
	// "[ javascript ]": {
	// 	"editor.formatOnSave": true
	// },
	"[ html ]": {
		"editor.formatOnSave": true
	},
	// Enable per-language
	"[php]": {
		"editor.formatOnSave": true
	},
	"editor.fontFamily": "'Dank Mono', Menlo, Monaco, 'Courier New', monospace",
	// "terminal.integrated.fontFamily": "'Dank Mono', 'Source Code Pro for Powerline'",
	"git.autofetch": true,
	"editor.insertSpaces": false,
	"editor.formatOnSave": true,
	"editor.formatOnPaste": true,
	"editor.tabSize": 4,
	"editor.detectIndentation": false,
	"editor.quickSuggestions": true,
	"[json]": {
		"editor.defaultFormatter": "vscode.json-language-features"
	},
	"prettier.useTabs": true,
	"prettier.tabWidth": 4,
	"prettier.singleQuote": true,
	"prettier.bracketSpacing": true,
	"[css]": {},
}`

**Expected behavior:**

On a save I expect the function

`	getUrl = (width, height) => {
`

To be
`	getUrl = ( width, height ) => {
`

**Actual behavior:**
However, the spaces are removed.  I don't know how to use wp-prettier instead of the default prettier and the wp-prettier documentation just points to prettier.

**Comment by scinos** [comment]
In your `package.json`, replace something like:

```
"wp-prettier": "^2.0.0",
```

with:

```
"prettier": "npm:wp-prettier@^2.0.0",
```

The trick is that the plugin you are using (https://github.com/prettier/prettier-vscode) will look for `./node_modules/prettier` and use it. The change above will force `npm` (or `yarn`, works with both) to install `wp-prettier` as if it were `prettier`.

**Comment by shivapoudel** [comment]
@scinos  No luck to resolve this space issue. In my `package.json`, I do have `"prettier": "npm:wp-prettier@2.0.5"` but still VSCode is removing spaces on save,

```
const defaultConfig = require('@wordpress/scripts/config/webpack.config');

module.exports = {
	...defaultConfig,
	entry: {
		index: __dirname + '/client/index.js',
	},
};
```

**Comment by Antonio-Laguna** [comment]
@shivapoudel did you manage to fix this? I have the exact same issue

**Comment by eduwass** [comment]
I don't know if it's just me but this sometimes does weird stuff for me, e.g: I use the `"parenSpacing": true,` directive and sometime it stops working (no spaces in parenthesis) and after reinstalling npm modules and activating/deactivating the VSCode Extension it starts working again... Haven't really found out what's going on yet.

**Comment by musosoft** [comment]
Guys I've had a similar issue and IIRC I fixed it by [forcing](https://github.com/musosoft/codewpcs/commit/f0e808b645d872a65244c8cf1874ea65adc44460#diff-a5de3e5871ffcc383a2294845bd3df25d3eeff6c29ad46e3a396577c413bf357R44-R46) the Prettier VS Code extension to it's [aliased](https://github.com/Automattic/wp-prettier/issues/21#issuecomment-634455484) node module. You can also try using [codewpcs](https://github.com/musosoft/codewpcs) to see if it works with my setup.
