### ISSUE TITLE
Does paren space work correctly inside tagged templates?

### ISSUE THREAD

**Issue by sirreal** [Automattic/calypso-prettier#28]
Via https://github.com/Automattic/wp-calypso/pull/42694#pullrequestreview-419011075

Looking at the prettier playground, it does appear to format these so perhaps inserting space in the `${}` is something `wp-prettier` is missing. [The prettier playground formats these lines identically](https://prettier.io/playground/#N4Igxg9gdgLgprEAuc0DOMAEBlADgQzDgHkAnAOQj0LkwF5MMBPAGzgBMA6dgSwDcABgB0oQmDFL4oaAGYRSAWySYAJMAAUuUhFxoAlHQB8m7bs480AYQgLcbeAH4A5Npj54ATXUBGABwAGdjgAcz0nJBcIN091fzC9AF8AbhFMNMwJKVl5JVVgTHVMLR00TD16QwKi0zRzKxs7OHhMB0xI6LgvP0CQsMxldvdO2L7y5JEBFKgQABoQHRgedGRQfFJtAHcABTWENGQQfBYN-CZ9uYAjSTAAaybqMB4oYOQJAFc4OYALGAUWAHUvjx4GgCERsHtgfxgUwDmA0OcQE80HBSDAtpJggp8MgZEcUXMAFZoAAeACFrncYNh8Ao4AAZJ5wXH4z4gYkk7BPYJsACKbyizKQeJYBJABFIKNIBwu+AucBYs3FpCeMH+PHYMC+yACc2KKP+klwBy0cClfGZcwAjgL4BiSgd8GgALRQOAcDhK0hwG08b0Y-BYnHC1lzFEKHivUgfMPcvm2oUisVuC7qzXapAAJjmmR4LG51gU2IOZoArEq3iiACpy-Yh0VsvgfACSUCCsGwYBVuBgAEE29gYKxE6yEgkgA), as I'd expect:

```js
const SpaceOrNoSpace = styled.div`
  transform: ${(props)=>(props.isComplete?'rotateY(180deg)':'rotateY(0)')};
  transform: ${ ( props ) => ( props.isComplete ? 'rotateY(180deg)' : 'rotateY(0)' ) };
`;
```

**Comment by sirreal** [comment]
@jsnajdr @scinos I'd be curious to get your thoughts on this. You can see the behavior in #29.

**Comment by scinos** [comment]
It comes from 

```
      parts = parts
        .slice(0, atPlaceholderIndex)
        .concat(["${", expression, "}" + suffix])
        .concat(rest);
```
(https://github.com/Automattic/wp-prettier/blob/wp-prettier-2.0.5/src/language-js/embed.js#L304)

It is missing `parenSpace`, I have a PR almost ready to fix it.

**Comment by jsnajdr** [comment]
Oh yes, that was found in Gutenberg code some time ago and I pushed a fix to the `wp-master` branch: https://github.com/Automattic/wp-prettier/commit/01fd780c7c5a8edd9e3ef7daea49e650fa42cee5

But then never got around to publish it -- you and @scinos took over 🙂 

The tagged templates are formatted by a completely different code path than regular template string without a tag. That's because the tagged template content can have a recognized format (CSS in CSS-in-JS libraries) and are formatted as such.

**Comment by jsnajdr** [comment]
> I have a PR almost ready to fix it.

@scinos If you're already done with the fix, you can compare with my version in https://github.com/Automattic/wp-prettier/commit/01fd780c7c5a8edd9e3ef7daea49e650fa42cee5 🙂 If you're not done yet, you can simply use the patch and just apply and release it.
